from deph import parser
from deph.policy import (FAIL, WARN, WAIVED, evaluate, exit_code,
                         grade_for_score, license_allowed, license_in,
                         normalize_severity, project_score, severity_rank,
                         Summary)


def make_doc(policy_text, generated_text):
    text = (policy_text +
            "\n// ---- generated by deph scan @ t — do not edit below ----\n" +
            generated_text)
    return parser.parse(text, path="test.deph")


def grade(project, findings):
    return grade_for_score(project_score(project, findings))


STANDARD_POLICY = """policy {
  fail vuln >= high
  warn vuln >= low
  fail license not [MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, MPL-2.0]
  warn lag >= major
}
"""


def test_high_vuln_judged_once_at_fail():
    """A high vuln matches both `fail >= high` and `warn >= low` but must
    yield exactly ONE finding, at fail level."""
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep axios 0.21.1 -> 1.18.1 license=MIT [vuln:high:GHSA-1111]
}
''')
    findings = evaluate(doc)
    vulns = [f for f in findings if f.kind == "vuln"]
    assert len(vulns) == 1
    assert vulns[0].level == FAIL
    assert vulns[0].id == "GHSA-1111"


def test_low_vuln_warns_only():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep foo 1.0.0 license=MIT [vuln:low:GHSA-2222]
}
''')
    findings = evaluate(doc)
    assert len(findings) == 1
    assert findings[0].level == WARN
    assert exit_code(findings) == 0


def test_moderate_aliases_to_medium():
    assert normalize_severity("moderate") == "medium"
    assert normalize_severity("MODERATE") == "medium"
    assert severity_rank("moderate") == severity_rank("medium")


def test_unknown_severity_never_crashes_and_never_matches():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep foo 1.0.0 license=MIT [vuln:catastrophic:GHSA-3333]
}
''')
    findings = evaluate(doc)  # must not raise
    assert findings == []


def test_spdx_or_passes_allowlist_with_either_alternative():
    allow = ["MIT", "Apache-2.0"]
    assert license_allowed("MIT OR Apache-2.0", allow)
    assert license_allowed("GPL-3.0 OR MIT", allow)
    assert license_allowed("MIT/Apache-2.0", allow)
    assert license_allowed("(MIT OR GPL-3.0)", allow)
    assert not license_allowed("GPL-3.0", allow)
    assert not license_allowed("GPL-3.0 OR AGPL-3.0", allow)


def test_spdx_and_requires_all_parts():
    allow = ["MIT", "Apache-2.0"]
    assert license_allowed("MIT AND Apache-2.0", allow)
    assert not license_allowed("MIT AND GPL-3.0", allow)
    # mixed: (MIT OR GPL-3.0) AND Apache-2.0
    assert license_allowed("(MIT OR GPL-3.0) AND Apache-2.0", allow)


def test_license_allow_case_insensitive():
    assert license_allowed("mit", ["MIT"])


def test_license_denylist_in():
    assert license_in("GPL-3.0", ["GPL-3.0"])
    assert license_in("MIT OR GPL-3.0", ["GPL-3.0"])
    assert not license_in("MIT", ["GPL-3.0"])


def test_disallowed_license_fails():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=pip {
  dep copyleft-lib 1.0.0 license=GPL-3.0-only
}
''')
    findings = evaluate(doc)
    assert len(findings) == 1
    assert findings[0].kind == "license"
    assert findings[0].level == FAIL
    assert exit_code(findings) == 1


def test_unknown_license_produces_no_finding():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=pip {
  dep mystery 1.0.0 license=unknown
}
''')
    assert evaluate(doc) == []


def test_lag_major_warns():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep old 1.0.0 -> 3.0.0 license=MIT [lag:major]
}
''')
    findings = evaluate(doc)
    assert len(findings) == 1
    assert findings[0].kind == "lag"
    assert findings[0].level == WARN


def test_lag_minor_below_threshold_no_finding():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep old 1.0.0 -> 1.1.0 license=MIT [lag:minor]
}
''')
    assert evaluate(doc) == []


def test_waived_finding_reports_waived_and_never_fails():
    doc = make_doc(STANDARD_POLICY + '\nwaive GHSA-1111 "accepted risk until Q3"\n', '''
project "a" ecosystem=npm {
  dep axios 0.21.1 -> 1.18.1 license=MIT [vuln:high:GHSA-1111]
}
''')
    findings = evaluate(doc)
    assert len(findings) == 1
    assert findings[0].level == WAIVED
    assert findings[0].waived_reason == "accepted risk until Q3"
    assert exit_code(findings) == 0


def test_waiver_on_license_finding_by_synthetic_id():
    doc = make_doc(STANDARD_POLICY + '\nwaive license:copyleft-lib "legal approved"\n', '''
project "a" ecosystem=pip {
  dep copyleft-lib 1.0.0 license=GPL-3.0-only
}
''')
    findings = evaluate(doc)
    assert findings[0].level == WAIVED


def test_summary_counts():
    doc = make_doc(STANDARD_POLICY + '\nwaive GHSA-3 "ok"\n', '''
project "a" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:high:GHSA-1]
  dep b 1.0.0 license=MIT [vuln:low:GHSA-2]
  dep c 1.0.0 license=MIT [vuln:critical:GHSA-3]
}
''')
    s = Summary.of(evaluate(doc))
    assert (s.fail, s.warn, s.waived) == (1, 1, 1)


def test_multiple_vulns_on_one_dep_each_judged():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep bad 1.0.0 license=MIT [vuln:high:GHSA-a, vuln:medium:GHSA-b]
}
''')
    findings = evaluate(doc)
    assert len(findings) == 2
    levels = {f.id: f.level for f in findings}
    assert levels == {"GHSA-a": FAIL, "GHSA-b": WARN}


def test_grades():
    doc = make_doc(STANDARD_POLICY, '''
project "clean" ecosystem=npm {
  dep fine 1.0.0 license=MIT
}
project "dirty" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:critical:GHSA-1]
  dep b 1.0.0 license=MIT [vuln:high:GHSA-2]
  dep c 1.0.0 license=GPL-3.0-only
}
''')
    findings = evaluate(doc)
    clean = next(p for p in doc.projects if p.name == "clean")
    dirty = next(p for p in doc.projects if p.name == "dirty")
    assert grade(clean, findings) == "A"
    assert grade(dirty, findings) == "F"


def test_waived_findings_dont_hurt_grade():
    doc = make_doc(STANDARD_POLICY + '\nwaive GHSA-1 "ok"\n', '''
project "a" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:critical:GHSA-1]
}
''')
    findings = evaluate(doc)
    assert grade(doc.projects[0], findings) == "A"


def test_transitive_flag_carried_to_finding():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep indirect 1.0.0 license=MIT transitive [vuln:high:GHSA-t]
}
''')
    findings = evaluate(doc)
    assert findings[0].transitive is True


# -- scoped rules -------------------------------------------------------------

SCOPED_POLICY = """policy {
  fail vuln >= high for direct
  warn vuln >= high for transitive
  fail license not [MIT] for prod
}
"""


def test_scope_direct_fails_transitive_only_warns():
    doc = make_doc(SCOPED_POLICY, '''
project "a" ecosystem=npm {
  dep mine 1.0.0 license=MIT [vuln:high:GHSA-1]
  dep theirs 1.0.0 license=MIT transitive [vuln:high:GHSA-2]
}
''')
    levels = {f.id: f.level for f in evaluate(doc)}
    assert levels == {"GHSA-1": FAIL, "GHSA-2": WARN}
    assert exit_code(evaluate(doc)) == 1


def test_scope_prod_ignores_dev_dependencies():
    doc = make_doc(SCOPED_POLICY, '''
project "a" ecosystem=npm {
  dep shipped 1.0.0 license=GPL-3.0-only
  dep buildonly 1.0.0 license=GPL-3.0-only dev
}
''')
    findings = [f for f in evaluate(doc) if f.kind == "license"]
    assert [f.dep for f in findings] == ["shipped"]


def test_unscoped_rule_applies_to_everything():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:high:GHSA-1]
  dep b 1.0.0 license=MIT transitive dev [vuln:high:GHSA-2]
}
''')
    assert all(f.level == FAIL for f in evaluate(doc) if f.kind == "vuln")


def test_dev_flag_reaches_the_finding():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep tool 1.0.0 license=MIT dev [vuln:high:GHSA-1]
}
''')
    assert evaluate(doc)[0].dev is True


# -- waiver expiry ------------------------------------------------------------

def test_waiver_applies_before_its_date():
    doc = make_doc(STANDARD_POLICY + '\nwaive GHSA-1 until 2030-01-01 "planned"\n', '''
project "a" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:critical:GHSA-1]
}
''')
    f = evaluate(doc, today="2026-07-27")[0]
    assert f.level == WAIVED and not f.waiver_expired


def test_expired_waiver_reports_again():
    """A permanent waiver is a permanent blind spot, so they can expire."""
    doc = make_doc(STANDARD_POLICY + '\nwaive GHSA-1 until 2026-01-01 "was planned"\n', '''
project "a" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:critical:GHSA-1]
}
''')
    findings = evaluate(doc, today="2026-07-27")
    assert findings[0].level == FAIL
    assert findings[0].waiver_expired
    assert findings[0].waived_reason == "was planned"     # kept for context
    assert exit_code(findings) == 1


def test_waiver_without_a_date_never_expires():
    doc = make_doc(STANDARD_POLICY + '\nwaive GHSA-1 "forever"\n', '''
project "a" ecosystem=npm {
  dep a 1.0.0 license=MIT [vuln:critical:GHSA-1]
}
''')
    assert evaluate(doc, today="2099-01-01")[0].level == WAIVED


# -- unresolved ---------------------------------------------------------------

UNRESOLVED_POLICY = """policy {
  fail vuln >= high
  warn unresolved >= 1
}
"""


def test_unresolved_lines_produce_a_finding():
    doc = make_doc(UNRESOLVED_POLICY, '''
project "a" ecosystem=pip manifest="requirements.txt" {
  dep pinned 1.0.0 license=MIT
  unresolved "flask>=2.0" reason=range name=flask
  unresolved "-r missing.txt" reason=missing name=missing.txt
}
''')
    findings = [f for f in evaluate(doc) if f.kind == "unresolved"]
    assert len(findings) == 1
    assert findings[0].level == WARN
    assert findings[0].detail == "2"
    assert "1 missing, 1 range" in findings[0].message


def test_no_unresolved_rule_means_no_finding():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=pip {
  dep pinned 1.0.0 license=MIT
  unresolved "flask>=2.0" reason=range name=flask
}
''')
    assert [f for f in evaluate(doc) if f.kind == "unresolved"] == []


def test_unresolved_can_fail_the_build():
    doc = make_doc("policy {\n  fail unresolved >= 3\n}\n", '''
project "a" ecosystem=pip {
  unresolved "a>=1" reason=range name=a
  unresolved "b>=1" reason=range name=b
  unresolved "c>=1" reason=range name=c
}
''')
    assert exit_code(evaluate(doc)) == 1


def test_coverage_reflects_unaudited_deps():
    from deph.policy import coverage
    doc = make_doc(STANDARD_POLICY, '''
project "half" ecosystem=pip {
  dep a 1.0.0 license=MIT
  unresolved "b>=1" reason=range name=b
}
''')
    assert coverage(doc.projects[0]) == 0.5


# -- remediation --------------------------------------------------------------

def test_fix_version_reaches_the_finding_and_message():
    doc = make_doc(STANDARD_POLICY, '''
project "a" ecosystem=npm {
  dep axios 0.21.1 license=MIT fix=0.21.2 [vuln:high:GHSA-1]
}
''')
    f = evaluate(doc)[0]
    assert f.fix == "0.21.2"
    assert "fixed in 0.21.2" in f.message


def test_advisory_urls():
    from deph.policy import advisory_url
    assert advisory_url("GHSA-x") == "https://github.com/advisories/GHSA-x"
    assert advisory_url("RUSTSEC-2021-0001") == \
        "https://osv.dev/vulnerability/RUSTSEC-2021-0001"
    assert advisory_url("lag:foo") is None
