import pytest

from deph import parser
from deph.parser import DephSyntaxError, Dep, Document, Project


SAMPLE = '''// deph v1 policy. `deph scan` rewrites everything below the marker;
// this block and the waivers below it are preserved verbatim.

policy {
  fail vuln     >= high
  warn vuln     >= low
  fail license  not [MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, MPL-2.0]
  warn lag      >= major
}

waive GHSA-xxxx-yyyy-zzzz "vendored code not exposed; upgrade planned Q3"

// ---- generated by deph scan @ 2026-07-27 10:00 UTC — do not edit below ----

project "web/frontend" ecosystem=npm manifest="package-lock.json" {
  dep axios 0.21.1 -> 1.18.1 license=MIT [vuln:high:GHSA-hfxv-24rg-xrqf, lag:major]
  dep follow-redirects 1.14.0 -> 1.16.0 license=MIT transitive [vuln:medium:GHSA-r4q5-vmmm-2653]
}
'''


def test_parse_sample():
    doc = parser.parse(SAMPLE, path="repo.deph")
    assert len(doc.policy) == 4
    assert doc.policy[0].action == "fail"
    assert doc.policy[0].subject == "vuln"
    assert doc.policy[0].op == ">="
    assert doc.policy[0].value == "high"
    assert doc.policy[2].op == "not"
    assert doc.policy[2].value == ["MIT", "Apache-2.0", "BSD-2-Clause",
                                   "BSD-3-Clause", "ISC", "MPL-2.0"]
    assert len(doc.waivers) == 1
    assert doc.waivers[0].id == "GHSA-xxxx-yyyy-zzzz"
    assert "vendored" in doc.waivers[0].reason
    assert doc.generated_at == "2026-07-27 10:00 UTC"
    assert len(doc.projects) == 1
    proj = doc.projects[0]
    assert proj.name == "web/frontend"
    assert proj.ecosystem == "npm"
    assert proj.manifest == "package-lock.json"
    assert len(proj.deps) == 2
    axios = proj.deps[0]
    assert axios.name == "axios"
    assert axios.version == "0.21.1"
    assert axios.latest == "1.18.1"
    assert axios.license == "MIT"
    assert not axios.transitive
    assert axios.tags[0].kind == "vuln"
    assert axios.tags[0].qualifier == "high"
    assert axios.tags[0].ident == "GHSA-hfxv-24rg-xrqf"
    assert axios.tags[1].kind == "lag"
    assert axios.tags[1].qualifier == "major"
    fr = proj.deps[1]
    assert fr.transitive
    assert fr.latest == "1.16.0"


def test_policy_only_file_is_valid():
    doc = parser.parse("policy {\n  fail vuln >= high\n}\n")
    assert len(doc.policy) == 1
    assert doc.projects == []
    assert not doc.has_generated_section


def test_empty_file_is_valid():
    doc = parser.parse("")
    assert doc.policy == []
    assert doc.projects == []


def test_header_preserved_byte_for_byte():
    doc = parser.parse(SAMPLE, path="repo.deph")
    marker_idx = SAMPLE.index("// ---- generated")
    assert doc.header_text == SAMPLE[:marker_idx]


def test_round_trip_zero_diff():
    """render(parse(x)) with the same timestamp must reproduce byte-identical text."""
    doc = parser.parse(SAMPLE, path="repo.deph")
    out = parser.render(doc, timestamp=doc.generated_at)
    assert out == SAMPLE
    # Round-trip again to be sure rendering is a fixed point.
    doc2 = parser.parse(out, path="repo.deph")
    assert parser.render(doc2, timestamp=doc2.generated_at) == out


def test_render_changes_only_timestamp():
    doc = parser.parse(SAMPLE, path="repo.deph")
    out = parser.render(doc, timestamp="2027-01-01 00:00 UTC")
    changed = [
        (a, b)
        for a, b in zip(SAMPLE.splitlines(), out.splitlines())
        if a != b
    ]
    assert len(changed) == 1
    assert "generated by deph scan" in changed[0][0]


def test_scoped_npm_package_names():
    text = ("// ---- generated by deph scan @ t — do not edit below ----\n"
            'project "a" ecosystem=npm {\n'
            '  dep @babel/core 7.0.0 -> 7.26.0 license=MIT\n'
            "}\n")
    doc = parser.parse(text)
    assert doc.projects[0].deps[0].name == "@babel/core"


def test_error_position_malformed_policy_rule():
    text = "policy {\n  fail vuln >= high\n  bogus vuln >= high\n}\n"
    with pytest.raises(DephSyntaxError) as ei:
        parser.parse(text, path="repo.deph")
    err = ei.value
    assert err.line == 3
    assert err.col == 3
    assert "repo.deph:3:3" in str(err)


def test_error_position_missing_comparator():
    text = "policy {\n  fail vuln high\n}\n"
    with pytest.raises(DephSyntaxError) as ei:
        parser.parse(text, path="x.deph")
    assert ei.value.line == 2
    assert "policy rule malformed" in str(ei.value)


def test_error_unterminated_string():
    with pytest.raises(DephSyntaxError) as ei:
        parser.parse('waive GHSA-1 "no closing quote\n', path="x.deph")
    assert ei.value.line == 1


def test_error_waiver_missing_reason():
    with pytest.raises(DephSyntaxError) as ei:
        parser.parse("waive GHSA-abcd-efgh-ijkl\n", path="x.deph")
    assert "quoted reason" in str(ei.value)


def test_error_unclosed_policy_block():
    with pytest.raises(DephSyntaxError) as ei:
        parser.parse("policy {\n  fail vuln >= high\n", path="x.deph")
    assert "unclosed policy block" in str(ei.value)


def test_error_in_generated_section_has_absolute_line():
    text = ("policy {\n"          # line 1
            "  fail vuln >= high\n"  # 2
            "}\n"                    # 3
            "// ---- generated by deph scan @ t — do not edit below ----\n"  # 4
            "\n"                     # 5
            "project \"a\" {\n"      # 6
            "  dep lonely\n"          # 7, missing its version
            "}\n")
    with pytest.raises(DephSyntaxError) as ei:
        parser.parse(text, path="x.deph")
    assert ei.value.line == 7


def test_unknown_dep_attrs_are_preserved():
    text = ("// ---- generated by deph scan @ t — do not edit below ----\n"
            'project "a" {\n'
            "  dep foo 1.0.0 license=MIT sha=abc123\n"
            "}\n")
    doc = parser.parse(text)
    dep = doc.projects[0].deps[0]
    assert dep.attrs == {"sha": "abc123"}
    assert "sha=abc123" in parser.render_dep(dep)


def test_unknown_tags_are_carried_through():
    text = ("// ---- generated by deph scan @ t — do not edit below ----\n"
            'project "a" {\n'
            "  dep foo 1.0.0 [futurething:whatever, vuln:low:GHSA-1]\n"
            "}\n")
    doc = parser.parse(text)
    tags = doc.projects[0].deps[0].tags
    assert tags[0].kind == "futurething"
    assert tags[1].kind == "vuln"


def test_comments_allowed_inside_blocks():
    text = ("policy {\n"
            "  // block critical stuff\n"
            "  fail vuln >= high // trailing comment\n"
            "}\n")
    doc = parser.parse(text)
    assert len(doc.policy) == 1


def test_lint_duplicate_project():
    text = ("// ---- generated by deph scan @ t — do not edit below ----\n"
            'project "a" { }\n'
            'project "a" { }\n')
    doc = parser.parse(text)
    issues = parser.lint(doc)
    assert any("duplicate project" in i.message and i.severity == "error"
               for i in issues)


def test_lint_unknown_severity():
    doc = parser.parse("policy {\n  fail vuln >= enormous\n}\n")
    issues = parser.lint(doc)
    assert any("unknown vulnerability severity" in i.message for i in issues)


def test_lint_unknown_subject_is_warning_not_error():
    doc = parser.parse("policy {\n  fail cosmic >= rays\n}\n")
    issues = parser.lint(doc)
    assert issues[0].severity == "warning"


def test_lint_license_rule_with_comparator_is_error():
    doc = parser.parse("policy {\n  fail license >= MIT\n}\n")
    issues = parser.lint(doc)
    assert any(i.severity == "error" for i in issues)


def test_writer_quotes_odd_licenses():
    dep = Dep(name="foo", version="1.0", license="MIT OR Apache-2.0")
    line = parser.render_dep(dep)
    assert 'license="MIT OR Apache-2.0"' in line
    # and it must parse back
    text = ("// ---- generated by deph scan @ t — do not edit below ----\n"
            'project "a" {\n' + line + "\n}\n")
    doc = parser.parse(text)
    assert doc.projects[0].deps[0].license == "MIT OR Apache-2.0"


def test_render_sorts_projects_deterministically():
    doc = Document(header_text="policy {\n  fail vuln >= high\n}\n")
    doc.projects = [Project(name="zeta", ecosystem="npm"),
                    Project(name="alpha", ecosystem="pip")]
    out = parser.render(doc, timestamp="t")
    assert out.index('project "alpha"') < out.index('project "zeta"')


def test_latest_omitted_when_current():
    dep = Dep(name="foo", version="1.0.0", latest="1.0.0", license="MIT")
    assert "->" not in parser.render_dep(dep)
