"""SARIF and CycloneDX output."""

import json

from deph import parser, policy, report

SAMPLE = '''policy {
  fail vuln >= high
  warn vuln >= low
  fail license not [MIT, Apache-2.0]
  warn unresolved >= 1
}

waive GHSA-waived "accepted, tracked in TICKET-1"

// ---- generated by deph scan @ 2026-07-27 10:00 UTC — do not edit below ----

project "web/frontend" ecosystem=npm manifest="web/frontend/package-lock.json" {
  dep axios 0.21.1 -> 1.18.1 license=MIT cwe=CWE-918 fix=0.21.2 [vuln:high:GHSA-hfxv]
  dep "@scope/pkg" 2.0.0 license=MIT transitive dev
  dep waivedpkg 1.0.0 license=MIT [vuln:critical:GHSA-waived]
  dep copyleft 1.0.0 license=GPL-3.0-only
  unresolved "flask>=2.0" reason=range name=flask
}
'''


def doc():
    return parser.parse(SAMPLE, path="repo.deph")


# -- SARIF --------------------------------------------------------------------

def test_sarif_shape():
    payload = report.sarif(doc(), deph_file="repo.deph")
    assert payload["version"] == "2.1.0"
    assert payload["$schema"].endswith("sarif-schema-2.1.0.json")
    run = payload["runs"][0]
    assert run["tool"]["driver"]["name"] == "deph"
    rule_ids = {r["id"] for r in run["tool"]["driver"]["rules"]}
    assert rule_ids == {"deph/vuln", "deph/license", "deph/unresolved"}
    assert json.dumps(payload)          # must be serializable


def test_sarif_levels_map_from_policy():
    results = report.sarif(doc())["runs"][0]["results"]
    by_id = {r["properties"]["dependency"]: r for r in results}
    assert by_id["axios"]["level"] == "error"
    assert by_id["copyleft"]["level"] == "error"
    # A waived finding stays visible as a note rather than disappearing.
    assert by_id["waivedpkg"]["level"] == "note"
    assert by_id["waivedpkg"]["properties"]["waivedReason"].startswith("accepted")


def test_sarif_carries_remediation_and_metadata():
    results = report.sarif(doc())["runs"][0]["results"]
    axios = next(r for r in results if r["properties"]["dependency"] == "axios")
    assert axios["properties"]["fixedIn"] == "0.21.2"
    assert axios["properties"]["cwe"] == "CWE-918"
    assert axios["properties"]["advisory"].endswith("GHSA-hfxv")
    assert axios["properties"]["manifest"] == "web/frontend/package-lock.json"


def test_sarif_points_at_the_dep_line():
    d = doc()
    results = report.sarif(d)["runs"][0]["results"]
    axios_dep = next(x for x in d.projects[0].deps if x.name == "axios")
    axios = next(r for r in results if r["properties"]["dependency"] == "axios")
    region = axios["locations"][0]["physicalLocation"]["region"]
    assert region["startLine"] == axios_dep.line


def test_sarif_fingerprints_are_stable_across_runs():
    first = report.sarif(doc())["runs"][0]["results"]
    second = report.sarif(doc())["runs"][0]["results"]
    assert ([r["partialFingerprints"]["dephFindingId"] for r in first]
            == [r["partialFingerprints"]["dephFindingId"] for r in second])


def test_sarif_includes_unresolved_so_partial_scans_are_visible():
    results = report.sarif(doc())["runs"][0]["results"]
    assert any(r["ruleId"] == "deph/unresolved" for r in results)


def test_sarif_of_empty_document():
    payload = report.sarif(parser.parse("policy {\n}\n", path="x.deph"))
    assert payload["runs"][0]["results"] == []


# -- CycloneDX ----------------------------------------------------------------

def test_cyclonedx_shape():
    bom = report.cyclonedx(doc(), timestamp="2026-07-27T10:00:00Z")
    assert bom["bomFormat"] == "CycloneDX"
    assert bom["specVersion"] == "1.5"
    assert bom["metadata"]["timestamp"] == "2026-07-27T10:00:00Z"
    assert bom["metadata"]["tools"][0]["name"] == "deph"
    assert json.dumps(bom)


def test_cyclonedx_components_and_purls():
    bom = report.cyclonedx(doc())
    by_name = {c["name"]: c for c in bom["components"]}
    assert by_name["axios"]["purl"] == "pkg:npm/axios@0.21.1"
    # Canonical form encodes the scope's @; see test_purl_canonical_form.
    assert by_name["@scope/pkg"]["purl"] == "pkg:npm/%40scope/pkg@2.0.0"
    assert by_name["axios"]["licenses"] == [{"expression": "MIT"}]
    # dev dependencies are optional scope, direct-ness is a property
    assert by_name["@scope/pkg"]["scope"] == "optional"
    assert by_name["axios"]["scope"] == "required"
    props = {p["name"]: p["value"] for p in by_name["@scope/pkg"]["properties"]}
    assert props["deph:direct"] == "false"


def test_purl_types_per_ecosystem():
    assert report.purl("pip", "pyyaml", "5.4") == "pkg:pypi/pyyaml@5.4"
    assert report.purl("cargo", "tokio", "1.8.0") == "pkg:cargo/tokio@1.8.0"
    assert report.purl("go", "rsc.io/quote", "v1.5.2") == \
        "pkg:golang/rsc.io/quote@v1.5.2"
    assert report.purl("gem", "rails", "7.0.4") == "pkg:gem/rails@7.0.4"
    assert report.purl("composer", "m/pkg", "1.0") == "pkg:composer/m/pkg@1.0"


def test_cyclonedx_vulnerabilities_reference_components():
    bom = report.cyclonedx(doc())
    vulns = {v["id"]: v for v in bom["vulnerabilities"]}
    assert vulns["GHSA-hfxv"]["affects"] == [{"ref": "pkg:npm/axios@0.21.1"}]
    assert vulns["GHSA-hfxv"]["ratings"][0]["severity"] == "high"
    assert vulns["GHSA-hfxv"]["recommendation"] == "Upgrade axios to 0.21.2"
    assert vulns["GHSA-hfxv"]["cwes"] == [918]


def test_cyclonedx_marks_waived_as_not_affected():
    bom = report.cyclonedx(doc())
    waived = next(v for v in bom["vulnerabilities"] if v["id"] == "GHSA-waived")
    assert waived["analysis"]["state"] == "not_affected"
    assert "TICKET-1" in waived["analysis"]["detail"]


def test_cyclonedx_omits_license_findings_from_vulnerabilities():
    bom = report.cyclonedx(doc())
    assert all(v["id"].startswith("GHSA-") for v in bom["vulnerabilities"])


def test_cyclonedx_unpinned_deps_are_absent_by_design():
    """An SBOM lists components; a range isn't one. The CLI warns about this."""
    bom = report.cyclonedx(doc())
    assert "flask" not in {c["name"] for c in bom["components"]}


def test_dumps_is_sorted_and_indented():
    text = report.dumps({"b": 1, "a": 2})
    assert text.startswith("{\n")
    assert text.index('"a"') < text.index('"b"')


def test_reports_accept_precomputed_findings():
    d = doc()
    findings = [f for f in policy.evaluate(d) if f.kind == "vuln"]
    payload = report.sarif(d, findings)
    assert {r["ruleId"] for r in payload["runs"][0]["results"]} == {"deph/vuln"}
