import http.client
import json
import threading

from deph import parser
from deph.studio import build_html, build_payload
from deph.studio.server import _make_handler

from http.server import ThreadingHTTPServer

SAMPLE = '''policy {
  fail vuln >= high
  warn vuln >= low
  fail license not [MIT, Apache-2.0]
  warn lag >= major
}

waive GHSA-wwww "vendored, not exposed"

// ---- generated by deph scan @ 2026-07-27 10:00 UTC — do not edit below ----

project "web/frontend" ecosystem=npm manifest="package-lock.json" {
  dep axios 0.21.1 -> 1.18.1 license=MIT [vuln:high:GHSA-hfxv-24rg-xrqf, lag:major]
  dep quiet 1.0.0 license=MIT
  dep waived-dep 2.0.0 license=MIT [vuln:critical:GHSA-wwww]
}

project "services/api" ecosystem=pip manifest="requirements.txt" {
  dep clean 1.0.0 license=MIT
}
'''


def test_payload_grades_and_findings():
    doc = parser.parse(SAMPLE, path="/x/repo.deph")
    payload = build_payload(doc)
    assert payload["file"] == "repo.deph"
    assert payload["generated_at"] == "2026-07-27 10:00 UTC"
    projects = {p["name"]: p for p in payload["projects"]}
    assert projects["services/api"]["grade"] == "A"
    frontend = projects["web/frontend"]
    assert frontend["grade"] in "BC"          # one high vuln + major lag
    axios = next(d for d in frontend["deps"] if d["name"] == "axios")
    kinds = {f["kind"] for f in axios["findings"]}
    assert kinds == {"vuln", "lag"}
    waived = next(d for d in frontend["deps"] if d["name"] == "waived-dep")
    assert waived["findings"][0]["level"] == "waived"
    assert waived["findings"][0]["waived_reason"] == "vendored, not exposed"
    assert payload["summary"]["fail"] == 1
    assert payload["summary"]["waived"] == 1


def test_build_html_is_self_contained_and_escaped():
    doc = parser.parse(SAMPLE, path="repo.deph")
    html = build_html(doc)
    assert "__DEPH_PAYLOAD__" not in html
    assert "GHSA-hfxv-24rg-xrqf" in html
    # embedded JSON must not be able to close the script tag
    payload_start = html.index("const DATA = ")
    payload_end = html.index(";\n", payload_start)
    assert "</script" not in html[payload_start:payload_end].lower()
    # no external fetches anywhere in the page
    head = html[:html.index("<body>")]
    assert "https://" not in head
    data = json.loads(html[payload_start + len("const DATA = "):payload_end]
                      .replace("<\\/", "</"))
    assert data["file"] == "repo.deph"


def test_server_serves_dashboard_from_file_at_request_time(tmp_path):
    path = tmp_path / "repo.deph"
    path.write_text(SAMPLE)
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), _make_handler(str(path)))
    port = httpd.server_address[1]
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    try:
        conn = http.client.HTTPConnection("127.0.0.1", port, timeout=5)
        conn.request("GET", "/")
        resp = conn.getresponse()
        body = resp.read().decode()
        assert resp.status == 200
        assert "GHSA-hfxv-24rg-xrqf" in body

        # edit the file, refresh: served content follows the file
        path.write_text(SAMPLE.replace("axios", "renamed-pkg"))
        conn.request("GET", "/")
        assert "renamed-pkg" in conn.getresponse().read().decode()

        # anything but / is a 404
        conn.request("GET", "/etc/passwd")
        assert conn.getresponse().status == 404
        conn.close()
    finally:
        httpd.shutdown()
        httpd.server_close()


def test_server_parse_error_page(tmp_path):
    path = tmp_path / "repo.deph"
    path.write_text("policy {\n  broken rule\n")
    httpd = ThreadingHTTPServer(("127.0.0.1", 0), _make_handler(str(path)))
    port = httpd.server_address[1]
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    try:
        conn = http.client.HTTPConnection("127.0.0.1", port, timeout=5)
        conn.request("GET", "/")
        resp = conn.getresponse()
        assert resp.status == 500
        assert "parse error" in resp.read().decode()
        conn.close()
    finally:
        httpd.shutdown()
        httpd.server_close()
