#!/usr/bin/env node
"use strict";

// Checks the wrapper end to end: it starts, it finds the vendored source, it
// scans a throwaway repo, and it passes the exit code through. The exit code
// is the whole point of `deph check` in CI, so a wrapper that swallowed it
// would be worse than no wrapper.

const { spawnSync } = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");

const BIN = path.join(__dirname, "..", "bin", "deph.js");
let failures = 0;

function run(args, opts) {
  return spawnSync(process.execPath, [BIN, ...args], {
    encoding: "utf8",
    ...opts,
  });
}

function check(name, condition, detail) {
  if (condition) {
    console.log(`ok   ${name}`);
  } else {
    failures += 1;
    console.error(`FAIL ${name}${detail ? `\n     ${detail}` : ""}`);
  }
}

const version = run(["--version"]);
check("--version exits 0", version.status === 0, version.stderr);
check("--version prints deph", /^deph \d+\.\d+\.\d+/.test(version.stdout.trim()),
  JSON.stringify(version.stdout));

const help = run(["--help"]);
check("--help lists the sbom command", help.stdout.includes("sbom"));

// A repo with a known-vulnerable pin, checked offline against a policy that
// must fail. Uses a cache dir that does not exist, so nothing can reach out.
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "deph-npm-smoke-"));
const env = { ...process.env, DEPH_CACHE_DIR: path.join(tmp, "cache") };

fs.writeFileSync(path.join(tmp, "repo.deph"), [
  "policy {",
  "  fail vuln >= high",
  "}",
  "",
  "// ---- generated by deph scan @ smoke — do not edit below ----",
  "",
  'project "app" ecosystem=npm manifest="package-lock.json" {',
  "  dep axios 0.21.1 license=MIT [vuln:high:GHSA-hfxv-24rg-xrqf]",
  "}",
  "",
].join("\n"));

const validate = run(["validate"], { cwd: tmp, env });
check("validate exits 0 on a good file", validate.status === 0, validate.stdout);

const failing = run(["check"], { cwd: tmp, env });
check("check exits 1 on a failing policy", failing.status === 1,
  `status=${failing.status}`);
check("check reports the advisory",
  failing.stdout.includes("GHSA-hfxv-24rg-xrqf"), failing.stdout);

const json = run(["check", "--format", "json"], { cwd: tmp, env });
check("check --format json exits 1 too", json.status === 1);
let parsed = null;
try {
  parsed = JSON.parse(json.stdout);
} catch (e) {
  check("check --format json emits parseable JSON", false, e.message);
}
if (parsed) {
  check("json schema is 2", parsed.schema === 2, String(parsed.schema));
  check("json reports not ok", parsed.ok === false);
}

const sbom = run(["sbom"], { cwd: tmp, env });
check("sbom exits 0", sbom.status === 0, sbom.stderr);
check("sbom is CycloneDX", sbom.stdout.includes('"bomFormat": "CycloneDX"'));

// Exit 2 is "couldn't judge", and must not be confused with a clean run.
const missing = fs.mkdtempSync(path.join(os.tmpdir(), "deph-npm-empty-"));
const noFile = run(["check"], { cwd: missing, env });
check("check exits 2 with no .deph file", noFile.status === 2,
  `status=${noFile.status}`);

const badPython = run(["--version"], {
  env: { ...process.env, DEPH_PYTHON: "definitely-not-a-python-abc123" },
});
check("a missing interpreter exits 2", badPython.status === 2,
  `status=${badPython.status}`);
check("a missing interpreter says so",
  /DEPH_PYTHON is set to/.test(badPython.stderr), badPython.stderr);

fs.rmSync(tmp, { recursive: true, force: true });
fs.rmSync(missing, { recursive: true, force: true });

console.log(failures ? `\n${failures} check(s) failed` : "\nall checks passed");
process.exit(failures ? 1 : 0);
