"""Tokenizer, parser, and writer for the .deph file format.

A .deph file has two regions. The header holds hand-written policy and waive
blocks, and is preserved byte-for-byte across rewrites. Everything below the
generated-marker comment belongs to `deph scan` and is regenerated wholesale.

Grammar reference: docs/SPEC.md.
"""

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

GENERATED_MARKER_PREFIX = "// ---- generated by deph scan"

# Ordered weakest to strongest; policy comparisons index into these.
VULN_LEVELS = ["low", "medium", "high", "critical"]
LAG_LEVELS = ["prerelease", "patch", "minor", "major"]

COMPARATORS = (">=", "<=", "==", "!=", ">", "<")

_ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


class DephSyntaxError(Exception):
    def __init__(self, message: str, file: str, line: int, col: int):
        self.message = message
        self.file = file
        self.line = line
        self.col = col
        super().__init__("%s at %s:%d:%d" % (message, file, line, col))


WORD = "WORD"
STRING = "STRING"
LBRACE = "LBRACE"
RBRACE = "RBRACE"
LBRACKET = "LBRACKET"
RBRACKET = "RBRACKET"
COMMA = "COMMA"
EQUALS = "EQUALS"
OP = "OP"          # >= <= == != > < ->
NEWLINE = "NEWLINE"
COMMENT = "COMMENT"
EOF = "EOF"

_PUNCT = {"{": LBRACE, "}": RBRACE, "[": LBRACKET, "]": RBRACKET, ",": COMMA}
_WORD_BREAK = set(" \t\r\n{}[],=\"<>")


@dataclass
class Token:
    type: str
    value: str
    line: int
    col: int


def tokenize(text: str, file: str = "<deph>", start_line: int = 1) -> List[Token]:
    """Newlines are emitted as tokens: they terminate statements."""
    tokens: List[Token] = []
    line = start_line
    col = 1
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch == "\n":
            tokens.append(Token(NEWLINE, "\n", line, col))
            line += 1
            col = 1
            i += 1
            continue
        if ch in " \t\r":
            i += 1
            col += 1
            continue
        if text.startswith("//", i):
            end = text.find("\n", i)
            if end == -1:
                end = n
            tokens.append(Token(COMMENT, text[i:end], line, col))
            col += end - i
            i = end
            continue
        if ch in _PUNCT:
            tokens.append(Token(_PUNCT[ch], ch, line, col))
            i += 1
            col += 1
            continue
        if ch == '"':
            j = i + 1
            buf = []
            while j < n and text[j] != '"':
                if text[j] == "\n":
                    raise DephSyntaxError("unterminated string", file, line, col)
                if text[j] == "\\" and j + 1 < n and text[j + 1] in ('"', "\\"):
                    buf.append(text[j + 1])
                    j += 2
                    continue
                buf.append(text[j])
                j += 1
            if j >= n:
                raise DephSyntaxError("unterminated string", file, line, col)
            tokens.append(Token(STRING, "".join(buf), line, col))
            col += (j + 1) - i
            i = j + 1
            continue
        # Before the single-char and word scans, or ">=" lexes as ">" + "=".
        two = text[i:i + 2]
        if two == "->" or two in COMPARATORS:
            tokens.append(Token(OP, two, line, col))
            i += 2
            col += 2
            continue
        if ch in "<>":
            tokens.append(Token(OP, ch, line, col))
            i += 1
            col += 1
            continue
        if ch == "=":
            tokens.append(Token(EQUALS, "=", line, col))
            i += 1
            col += 1
            continue
        # Permissive on purpose, so @scope/pkg, 1.0.0-beta.1, GHSA ids and
        # vuln:high:GHSA-... tags each lex as one token.
        j = i
        while j < n and text[j] not in _WORD_BREAK:
            if text.startswith("//", j):
                break
            j += 1
        if j == i:
            raise DephSyntaxError("unexpected character %r" % ch, file, line, col)
        tokens.append(Token(WORD, text[i:j], line, col))
        col += j - i
        i = j
    tokens.append(Token(EOF, "", line, col))
    return tokens


# Which dependencies a rule applies to. A rule with no `for` clause applies to
# everything; `for direct` and `for prod` let a team fail on their own code's
# dependencies while only warning about the tail behind them.
SCOPES = ("direct", "transitive", "dev", "prod")


@dataclass
class PolicyRule:
    action: str            # "fail" | "warn"
    subject: str           # "vuln" | "lag" | "license" | "unresolved"
    op: str                # a comparator, or "not" / "in" for list membership
    value: Any             # str for comparators, List[str] for not/in
    scopes: List[str] = field(default_factory=list)   # from a `for` clause
    line: int = 0
    col: int = 0

    def applies_to(self, direct: bool, dev: bool) -> bool:
        for scope in self.scopes:
            if scope == "direct" and not direct:
                return False
            if scope == "transitive" and direct:
                return False
            if scope == "dev" and not dev:
                return False
            if scope == "prod" and dev:
                return False
        return True


@dataclass
class Waiver:
    id: str
    reason: str
    until: Optional[str] = None   # ISO date; the waiver stops applying after it
    line: int = 0
    col: int = 0

    def expired(self, today: str) -> bool:
        return bool(self.until) and today > self.until


@dataclass
class Tag:
    """A bracketed finding on a dep line: vuln:high:GHSA-x, lag:major."""
    kind: str
    parts: List[str] = field(default_factory=list)
    line: int = 0
    col: int = 0

    @property
    def qualifier(self) -> Optional[str]:
        return self.parts[0] if self.parts else None

    @property
    def ident(self) -> Optional[str]:
        return self.parts[1] if len(self.parts) > 1 else None

    def render(self) -> str:
        return ":".join([self.kind] + self.parts)


@dataclass
class Dep:
    name: str
    version: str
    latest: Optional[str] = None       # set only when outdated
    license: Optional[str] = None
    transitive: bool = False
    dev: bool = False
    tags: List[Tag] = field(default_factory=list)
    attrs: Dict[str, str] = field(default_factory=dict)  # unknown, round-tripped
    line: int = 0
    col: int = 0

    @property
    def fix(self) -> Optional[str]:
        """Lowest version that clears every advisory on this dep, if known."""
        return self.attrs.get("fix")


@dataclass
class UnresolvedEntry:
    """A manifest line deph could not pin to a version.

    These exist so a scan can never quietly shrink. Without them a
    requirements.txt of six ranges audits as a clean, empty project.
    """
    spec: str
    reason: str = "unparsed"
    name: str = ""
    attrs: Dict[str, str] = field(default_factory=dict)
    line: int = 0
    col: int = 0


@dataclass
class Project:
    name: str
    ecosystem: str = ""
    manifest: str = ""
    deps: List[Dep] = field(default_factory=list)
    unresolved: List[UnresolvedEntry] = field(default_factory=list)
    attrs: Dict[str, str] = field(default_factory=dict)
    line: int = 0
    col: int = 0


@dataclass
class Document:
    path: str = "<deph>"
    header_text: str = ""              # verbatim, everything above the marker
    policy: List[PolicyRule] = field(default_factory=list)
    waivers: List[Waiver] = field(default_factory=list)
    projects: List[Project] = field(default_factory=list)
    generated_at: Optional[str] = None  # opaque timestamp from the marker line
    has_generated_section: bool = False


class _Parser:
    def __init__(self, tokens: List[Token], file: str):
        self.tokens = tokens
        self.file = file
        self.pos = 0

    def peek(self) -> Token:
        return self.tokens[self.pos]

    def next(self) -> Token:
        tok = self.tokens[self.pos]
        if tok.type != EOF:
            self.pos += 1
        return tok

    def error(self, message: str, tok: Optional[Token] = None) -> DephSyntaxError:
        tok = tok or self.peek()
        return DephSyntaxError(message, self.file, tok.line, tok.col)

    def expect(self, type_: str, what: str) -> Token:
        tok = self.peek()
        if tok.type != type_:
            raise self.error("expected %s, found %r" % (what, tok.value or tok.type))
        return self.next()

    def skip_blank(self):
        while self.peek().type in (NEWLINE, COMMENT):
            self.next()

    def skip_newlines(self):
        while self.peek().type == NEWLINE:
            self.next()

    def at_line_end(self) -> bool:
        return self.peek().type in (NEWLINE, COMMENT, EOF, RBRACE)

    def end_statement(self):
        if self.peek().type == COMMENT:
            self.next()
        if self.peek().type == NEWLINE:
            self.next()
        elif self.peek().type not in (EOF, RBRACE):
            raise self.error(
                "unexpected %r after end of statement" % self.peek().value)

    def parse_header(self, doc: Document):
        while True:
            self.skip_blank()
            tok = self.peek()
            if tok.type == EOF:
                return
            if tok.type != WORD:
                raise self.error("expected 'policy' or 'waive', found %r"
                                 % (tok.value or tok.type))
            if tok.value == "policy":
                self.parse_policy_block(doc)
            elif tok.value == "waive":
                doc.waivers.append(self.parse_waive())
            else:
                raise self.error(
                    "unknown top-level keyword %r (expected 'policy' or 'waive')"
                    % tok.value)

    def parse_policy_block(self, doc: Document):
        self.expect(WORD, "'policy'")
        self.skip_blank()
        self.expect(LBRACE, "'{'")
        while True:
            self.skip_blank()
            tok = self.peek()
            if tok.type == RBRACE:
                self.next()
                return
            if tok.type == EOF:
                raise self.error("unclosed policy block (missing '}')", tok)
            doc.policy.append(self.parse_policy_rule())

    def parse_policy_rule(self) -> PolicyRule:
        start = self.peek()
        action_tok = self.expect(WORD, "policy rule action ('fail' or 'warn')")
        if action_tok.value not in ("fail", "warn"):
            raise self.error("policy rule malformed", action_tok)
        subject_tok = self.expect(WORD, "policy rule subject (e.g. 'vuln')")
        tok = self.peek()
        if tok.type == OP and tok.value in COMPARATORS:
            self.next()
            value_tok = self.peek()
            if value_tok.type != WORD:
                raise self.error("policy rule malformed", start)
            self.next()
            rule = PolicyRule(action_tok.value, subject_tok.value, tok.value,
                              value_tok.value, line=start.line, col=start.col)
        elif tok.type == WORD and tok.value in ("not", "in"):
            self.next()
            values = self.parse_value_list()
            rule = PolicyRule(action_tok.value, subject_tok.value, tok.value,
                              values, line=start.line, col=start.col)
        else:
            raise self.error("policy rule malformed", start)
        rule.scopes = self.parse_scopes()
        self.end_statement()
        return rule

    def parse_scopes(self) -> List[str]:
        tok = self.peek()
        if tok.type != WORD or tok.value != "for":
            return []
        self.next()
        scopes: List[str] = []
        while True:
            scope_tok = self.peek()
            if scope_tok.type != WORD:
                raise self.error("expected a scope after 'for' (one of: %s)"
                                 % ", ".join(SCOPES))
            self.next()
            scopes.append(scope_tok.value)
            if self.peek().type == COMMA:
                self.next()
                continue
            break
        return scopes

    def parse_value_list(self) -> List[str]:
        self.expect(LBRACKET, "'['")
        values: List[str] = []
        self.skip_newlines()
        while self.peek().type != RBRACKET:
            tok = self.peek()
            if tok.type in (WORD, STRING):
                values.append(self.next().value)
            else:
                raise self.error("expected value in list, found %r"
                                 % (tok.value or tok.type))
            self.skip_newlines()
            if self.peek().type == COMMA:
                self.next()
                self.skip_newlines()
            elif self.peek().type != RBRACKET:
                raise self.error("expected ',' or ']' in list")
        self.next()
        return values

    def parse_waive(self) -> Waiver:
        start = self.expect(WORD, "'waive'")
        id_tok = self.peek()
        if id_tok.type not in (WORD, STRING):
            raise self.error("malformed waiver: expected an advisory id", start)
        self.next()
        until: Optional[str] = None
        tok = self.peek()
        if tok.type == WORD and tok.value == "until":
            self.next()
            date_tok = self.peek()
            if date_tok.type not in (WORD, STRING):
                raise self.error("malformed waiver: expected a date after 'until'")
            self.next()
            until = date_tok.value
            if not _ISO_DATE_RE.match(until):
                raise self.error(
                    "malformed waiver: 'until' wants a YYYY-MM-DD date, got %r"
                    % until, date_tok)
        reason_tok = self.peek()
        if reason_tok.type != STRING:
            raise self.error(
                'malformed waiver: expected a quoted reason after %r' % id_tok.value,
                reason_tok if reason_tok.type != NEWLINE else start)
        self.next()
        self.end_statement()
        return Waiver(id_tok.value, reason_tok.value, until,
                      start.line, start.col)

    def parse_generated(self, doc: Document):
        while True:
            self.skip_blank()
            tok = self.peek()
            if tok.type == EOF:
                return
            if tok.type != WORD or tok.value != "project":
                raise self.error("expected 'project', found %r"
                                 % (tok.value or tok.type))
            doc.projects.append(self.parse_project())

    def parse_project(self) -> Project:
        start = self.expect(WORD, "'project'")
        name_tok = self.peek()
        if name_tok.type not in (STRING, WORD):
            raise self.error("expected project name", name_tok)
        self.next()
        proj = Project(name=name_tok.value, line=start.line, col=start.col)
        while self.peek().type == WORD:
            key_tok = self.next()
            self.expect(EQUALS, "'=' after project attribute %r" % key_tok.value)
            val_tok = self.peek()
            if val_tok.type not in (WORD, STRING):
                raise self.error("expected value for attribute %r" % key_tok.value)
            self.next()
            if key_tok.value == "ecosystem":
                proj.ecosystem = val_tok.value
            elif key_tok.value == "manifest":
                proj.manifest = val_tok.value
            else:
                proj.attrs[key_tok.value] = val_tok.value
        self.expect(LBRACE, "'{'")
        while True:
            self.skip_blank()
            tok = self.peek()
            if tok.type == RBRACE:
                self.next()
                return proj
            if tok.type == EOF:
                raise self.error("unclosed project block (missing '}')", tok)
            if tok.type == WORD and tok.value == "dep":
                proj.deps.append(self.parse_dep())
            elif tok.type == WORD and tok.value == "unresolved":
                proj.unresolved.append(self.parse_unresolved())
            else:
                raise self.error(
                    "expected 'dep' or 'unresolved' inside project block, "
                    "found %r" % (tok.value or tok.type))

    def _expect_value(self, what: str) -> Token:
        # WORD or STRING: the writer quotes values that aren't plain words.
        tok = self.peek()
        if tok.type not in (WORD, STRING):
            raise self.error("expected %s, found %r" % (what, tok.value or tok.type))
        return self.next()

    def parse_dep(self) -> Dep:
        start = self.expect(WORD, "'dep'")
        name_tok = self._expect_value("dependency name")
        version_tok = self._expect_value("dependency version")
        dep = Dep(name=name_tok.value, version=version_tok.value,
                  line=start.line, col=start.col)
        while not self.at_line_end():
            tok = self.peek()
            if tok.type == OP and tok.value == "->":
                self.next()
                dep.latest = self._expect_value("latest version after '->'").value
            elif tok.type == WORD and tok.value == "transitive":
                self.next()
                dep.transitive = True
            elif tok.type == WORD and tok.value == "dev":
                self.next()
                dep.dev = True
            elif tok.type == WORD:
                key_tok = self.next()
                self.expect(EQUALS, "'=' after attribute %r" % key_tok.value)
                val_tok = self.peek()
                if val_tok.type not in (WORD, STRING):
                    raise self.error("expected value for attribute %r" % key_tok.value)
                self.next()
                if key_tok.value == "license":
                    dep.license = val_tok.value
                else:
                    dep.attrs[key_tok.value] = val_tok.value
            elif tok.type == LBRACKET:
                dep.tags = self.parse_tag_list()
            else:
                raise self.error("unexpected %r in dep line" % (tok.value or tok.type))
        self.end_statement()
        return dep

    def parse_unresolved(self) -> UnresolvedEntry:
        start = self.expect(WORD, "'unresolved'")
        spec_tok = self._expect_value("the unresolved requirement text")
        entry = UnresolvedEntry(spec=spec_tok.value, line=start.line,
                                col=start.col)
        while not self.at_line_end():
            key_tok = self.peek()
            if key_tok.type != WORD:
                raise self.error("unexpected %r in unresolved line"
                                 % (key_tok.value or key_tok.type))
            self.next()
            self.expect(EQUALS, "'=' after attribute %r" % key_tok.value)
            val_tok = self._expect_value("value for %r" % key_tok.value)
            if key_tok.value == "reason":
                entry.reason = val_tok.value
            elif key_tok.value == "name":
                entry.name = val_tok.value
            else:
                entry.attrs[key_tok.value] = val_tok.value
        self.end_statement()
        return entry

    def parse_tag_list(self) -> List[Tag]:
        self.expect(LBRACKET, "'['")
        tags: List[Tag] = []
        self.skip_newlines()
        while self.peek().type != RBRACKET:
            tok = self.peek()
            if tok.type != WORD:
                raise self.error("expected tag in list, found %r"
                                 % (tok.value or tok.type))
            self.next()
            parts = tok.value.split(":")
            tags.append(Tag(kind=parts[0], parts=parts[1:],
                            line=tok.line, col=tok.col))
            self.skip_newlines()
            if self.peek().type == COMMA:
                self.next()
                self.skip_newlines()
            elif self.peek().type != RBRACKET:
                raise self.error("expected ',' or ']' in tag list")
        self.next()
        return tags


def _split_at_marker(text: str) -> Tuple[str, Optional[str], Optional[str], int]:
    """-> (header, marker timestamp, generated text, generated start line).

    The header comes back verbatim, including the newline before the marker.
    """
    lines = text.splitlines(keepends=True)
    for idx, line in enumerate(lines):
        if line.strip().startswith(GENERATED_MARKER_PREFIX):
            header = "".join(lines[:idx])
            generated = "".join(lines[idx + 1:])
            stripped = line.strip()
            ts: Optional[str] = None
            if "@" in stripped:
                after = stripped.split("@", 1)[1]
                # Drop the trailing "do not edit below" suffix, keep the date.
                for sep in ("—", "--"):
                    if sep in after:
                        after = after.split(sep, 1)[0]
                        break
                ts = after.strip()
            return header, ts, generated, idx + 2
    return text, None, None, 0


def parse(text: str, path: str = "<deph>") -> Document:
    doc = Document(path=path)
    header, ts, generated, gen_start = _split_at_marker(text)
    doc.header_text = header
    doc.generated_at = ts
    doc.has_generated_section = generated is not None

    header_tokens = tokenize(header, file=path, start_line=1)
    _Parser(header_tokens, path).parse_header(doc)

    if generated is not None:
        gen_tokens = tokenize(generated, file=path, start_line=gen_start)
        _Parser(gen_tokens, path).parse_generated(doc)
    return doc


def parse_file(path: str) -> Document:
    with open(path, "r", encoding="utf-8") as f:
        return parse(f.read(), path=path)


def _needs_quotes(value: str) -> bool:
    if value == "":
        return True
    if "//" in value:          # would open a comment mid-line
        return True
    for ch in value:
        if ch in _WORD_BREAK or ch == '"':
            return True
    return False


def _render_value(value: str) -> str:
    if _needs_quotes(value):
        return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')
    return value


def render_dep(dep: Dep) -> str:
    # Quote anything that won't round-trip as a bare word: a lockfile with an
    # odd package name must not produce a .deph we can't read back.
    parts = ["  dep", _render_value(dep.name), _render_value(dep.version)]
    if dep.latest and dep.latest != dep.version:
        parts.append("->")
        parts.append(_render_value(dep.latest))
    if dep.license is not None:
        parts.append("license=%s" % _render_value(dep.license))
    for key in sorted(dep.attrs):
        parts.append("%s=%s" % (key, _render_value(dep.attrs[key])))
    if dep.transitive:
        parts.append("transitive")
    if dep.dev:
        parts.append("dev")
    if dep.tags:
        parts.append("[%s]" % ", ".join(t.render() for t in dep.tags))
    return " ".join(parts)


def render_unresolved(entry: UnresolvedEntry) -> str:
    parts = ["  unresolved", _render_value(entry.spec),
             "reason=%s" % _render_value(entry.reason)]
    if entry.name:
        parts.append("name=%s" % _render_value(entry.name))
    for key in sorted(entry.attrs):
        parts.append("%s=%s" % (key, _render_value(entry.attrs[key])))
    return " ".join(parts)


def render_project(proj: Project) -> str:
    head = ['project "%s"' % proj.name]
    if proj.ecosystem:
        head.append("ecosystem=%s" % _render_value(proj.ecosystem))
    if proj.manifest:
        head.append('manifest="%s"' % proj.manifest)
    for key in sorted(proj.attrs):
        head.append("%s=%s" % (key, _render_value(proj.attrs[key])))
    lines = [" ".join(head) + " {"]
    for dep in proj.deps:
        lines.append(render_dep(dep))
    for entry in proj.unresolved:
        lines.append(render_unresolved(entry))
    lines.append("}")
    return "\n".join(lines)


def render(doc: Document, timestamp: Optional[str] = None) -> str:
    """Header verbatim, generated section rebuilt.

    Projects are sorted by name so repeat scans of unchanged dependencies
    produce no diff beyond the timestamp.
    """
    header = doc.header_text
    if not doc.has_generated_section and not doc.projects:
        return header
    if header and not header.endswith("\n"):
        header += "\n"
    if header and not header.endswith("\n\n"):
        header += "\n"
    ts = timestamp if timestamp is not None else (doc.generated_at or "")
    out = [header]
    out.append("// ---- generated by deph scan @ %s — do not edit below ----\n" % ts)
    for proj in sorted(doc.projects, key=lambda p: p.name):
        out.append("\n")
        out.append(render_project(proj))
        out.append("\n")
    return "".join(out)


KNOWN_SUBJECTS = {"vuln", "lag", "license", "unresolved"}
KNOWN_VULN_VALUES = set(VULN_LEVELS)
KNOWN_LAG_VALUES = set(LAG_LEVELS)


@dataclass
class LintIssue:
    severity: str  # "error" | "warning"
    message: str
    line: int
    col: int

    def format(self, path: str) -> str:
        return "%s:%d:%d: %s: %s" % (path, self.line, self.col,
                                     self.severity, self.message)


def lint(doc: Document, today: Optional[str] = None) -> List[LintIssue]:
    issues: List[LintIssue] = []
    for rule in doc.policy:
        for scope in rule.scopes:
            if scope not in SCOPES:
                issues.append(LintIssue(
                    "error", "unknown scope %r after 'for' (expected one of: %s)"
                    % (scope, ", ".join(SCOPES)), rule.line, rule.col))
        if "direct" in rule.scopes and "transitive" in rule.scopes:
            issues.append(LintIssue(
                "warning", "'for direct, transitive' can never match; drop the "
                "'for' clause to apply to both", rule.line, rule.col))
        if "dev" in rule.scopes and "prod" in rule.scopes:
            issues.append(LintIssue(
                "warning", "'for dev, prod' can never match; drop the 'for' "
                "clause to apply to both", rule.line, rule.col))
        if rule.subject not in KNOWN_SUBJECTS:
            issues.append(LintIssue(
                "warning", "unknown policy subject %r (known: %s)"
                % (rule.subject, ", ".join(sorted(KNOWN_SUBJECTS))),
                rule.line, rule.col))
            continue
        if rule.subject == "unresolved" and rule.op in COMPARATORS:
            if not str(rule.value).isdigit():
                issues.append(LintIssue(
                    "error", "unresolved rules compare against a count, got %r"
                    % rule.value, rule.line, rule.col))
        if rule.subject == "vuln" and rule.op in COMPARATORS:
            if rule.value not in KNOWN_VULN_VALUES:
                issues.append(LintIssue(
                    "error", "unknown vulnerability severity %r (expected one of: %s)"
                    % (rule.value, ", ".join(VULN_LEVELS)), rule.line, rule.col))
        if rule.subject == "lag" and rule.op in COMPARATORS:
            if rule.value not in KNOWN_LAG_VALUES:
                issues.append(LintIssue(
                    "error", "unknown lag level %r (expected one of: %s)"
                    % (rule.value, ", ".join(LAG_LEVELS)), rule.line, rule.col))
        if rule.subject == "license" and rule.op not in ("not", "in"):
            issues.append(LintIssue(
                "error", "license rules use 'not [...]' or 'in [...]', not %r"
                % rule.op, rule.line, rule.col))
    seen_waivers: Dict[str, Waiver] = {}
    for w in doc.waivers:
        if not w.reason.strip():
            issues.append(LintIssue(
                "warning", "waiver %s has an empty reason" % w.id, w.line, w.col))
        if today and w.expired(today):
            issues.append(LintIssue(
                "warning", "waiver %s expired on %s; its findings are being "
                "reported again" % (w.id, w.until), w.line, w.col))
        if w.id in seen_waivers:
            issues.append(LintIssue(
                "warning", "duplicate waiver %s (first at line %d)"
                % (w.id, seen_waivers[w.id].line), w.line, w.col))
        else:
            seen_waivers[w.id] = w
    seen_projects: Dict[str, Project] = {}
    for p in doc.projects:
        if p.name in seen_projects:
            issues.append(LintIssue(
                "error", "duplicate project \"%s\" (first at line %d)"
                % (p.name, seen_projects[p.name].line), p.line, p.col))
        else:
            seen_projects[p.name] = p
    return issues
